"""User-facing CLI: render one factory in isolation.

    python -m infinigen.maquette.pipeline.preview \
        --factory LowPolyPalmTreeFactory \
        --seed 7 \
        --out /tmp/palm.png \
        [--archetype coconut] [--blend /tmp/palm.blend] [--samples 64]

Companion script that runs inside Blender: ``preview_blender.py``.
This module is the host-side wrapper — it argparses, sanity-checks
the factory class name, then subprocesses to blender.

Why this exists: every prior factory iteration loop required writing
a one-off build script, running the full pipeline (terrain + lighting
+ composition + multi-angle), and waiting ~30s for a render. Preview
collapses that to ~5s — write factory, run preview, inspect PNG.
Also the backbone for an autogenerated thumbnail grid in
FACTORIES_GUIDE.md (future).
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


_HERE = Path(__file__).resolve().parent
_INNER_SCRIPT = _HERE / "preview_blender.py"


def render_factory(
    factory_name: str,
    out_png: Path,
    *,
    seed: int = 0,
    archetype: str | None = None,
    preset: str | None = None,
    blend_path: Path | None = None,
    metadata_path: Path | None = None,
    samples: int = 32,
    size: int = 720,
    blender_bin: str = "blender",
    timeout_seconds: int = 120,
) -> subprocess.CompletedProcess:
    """Programmatic API. Returns the CompletedProcess so callers can
    surface stderr on failure. The thumbnail-grid generator will call
    this in a loop and just inspect ``returncode``."""
    if shutil.which(blender_bin) is None:
        raise RuntimeError(
            f"`{blender_bin}` not on PATH. Install Blender or pass "
            f"--blender to point at the binary."
        )
    if not _INNER_SCRIPT.is_file():
        raise RuntimeError(f"missing inner script: {_INNER_SCRIPT}")
    out_png.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        blender_bin, "--background", "--python", str(_INNER_SCRIPT), "--",
        "--factory", factory_name,
        "--seed", str(seed),
        "--out", str(out_png),
        "--samples", str(samples),
        "--size", str(size),
    ]
    if archetype:
        cmd += ["--archetype", archetype]
    if preset:
        cmd += ["--preset", preset]
    if blend_path:
        blend_path.parent.mkdir(parents=True, exist_ok=True)
        cmd += ["--blend", str(blend_path)]
    if metadata_path:
        metadata_path.parent.mkdir(parents=True, exist_ok=True)
        cmd += ["--metadata", str(metadata_path)]
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
        env=os.environ.copy(),
    )


def _maybe_list_presets(argv: list[str]) -> bool:
    """Short-circuit if --list-presets was passed. Returns True if a list
    was printed (and the caller should exit 0). Avoids argparse's required
    --out check on a query-only invocation."""
    if "--list-presets" not in argv:
        return False
    from infinigen.maquette.factory_presets import list_presets
    # Optional `--factory NAME` filter; everything else is ignored.
    factory_filter: str | None = None
    for i, a in enumerate(argv):
        if a == "--factory" and i + 1 < len(argv):
            factory_filter = argv[i + 1]
            break
    if factory_filter:
        rows = list_presets(factory_filter)
        if not rows:
            print(f"No presets registered for {factory_filter}")
            return True
        print(f"{factory_filter}:")
        for name in rows:
            print(f"  {name}")
    else:
        all_rows = list_presets()
        for fac, names in sorted(all_rows.items()):
            print(f"{fac}:")
            for name in names:
                print(f"  {name}")
    return True


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    if _maybe_list_presets(argv):
        return 0

    parser = argparse.ArgumentParser(
        prog="python -m infinigen.maquette.pipeline.preview",
        description="Render a single Maquette factory to a PNG thumbnail.",
    )
    parser.add_argument("--factory", required=True,
                        help="Factory class name, e.g. LowPolyPalmTreeFactory")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--archetype", default=None)
    parser.add_argument("--preset", default=None,
                        help="Named preset from infinigen.maquette.factory_presets. "
                             "Run with `--list-presets` to see options.")
    parser.add_argument("--list-presets", action="store_true",
                        help="Print available presets (for --factory if given, "
                             "else all) and exit. No render.")
    parser.add_argument("--out", required=True, type=Path,
                        help="PNG output path")
    parser.add_argument("--blend", type=Path, default=None,
                        help="Optional .blend save path")
    parser.add_argument("--metadata", type=Path, default=None,
                        help="Optional JSON metadata path")
    parser.add_argument("--samples", type=int, default=32,
                        help="Cycles samples (default 32 = ~5s render)")
    parser.add_argument("--size", type=int, default=720)
    parser.add_argument("--blender", default="blender",
                        help="Blender executable (default: 'blender' on PATH)")
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--quiet", action="store_true",
                        help="Suppress blender stdout on success")
    args = parser.parse_args(argv)

    result = render_factory(
        factory_name=args.factory,
        out_png=args.out,
        seed=args.seed,
        archetype=args.archetype,
        preset=args.preset,
        blend_path=args.blend,
        metadata_path=args.metadata,
        samples=args.samples,
        size=args.size,
        blender_bin=args.blender,
        timeout_seconds=args.timeout,
    )
    if result.returncode != 0:
        # Surface blender's complaint — the inner script prints its own
        # FAIL: line, but blender wraps everything in its banner so the
        # raw stderr is what tells you what actually broke.
        print(result.stdout, file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        return result.returncode
    if not args.quiet:
        # The inner script's `OK: <path>` line is on the last stdout line.
        # Surfacing it makes shell-pipelining the result trivial.
        for line in result.stdout.splitlines()[-6:]:
            if line.startswith("OK:") or line.startswith("FAIL:"):
                print(line)
                break
    return 0


if __name__ == "__main__":
    sys.exit(main())
